[package]

name = "cpclib-tokens"
version.workspace = true
description = "cpclib libraries related to assembly tokens. Only structures are provided there. Intelligence is within cpclib-asm"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[package.metadata.workspaces]
independent = true

[dependencies]
cpclib-sna.workspace = true
cpclib-common.workspace = true

ahash.workspace = true
beef.workspace = true
cfg-if.workspace = true
delegate.workspace = true
either.workspace = true
evalexpr.workspace = true
ordered-float.workspace = true
memchr.workspace = true
paste.workspace = true
regex.workspace = true
remain.workspace = true
serde.workspace = true

[build-dependencies]
built.workspace = true


[features]
default = []
rayon = ["cpclib-common/rayon"]
