[package]
name = "cpclib-basmdoc"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true

[dependencies]
cpclib-asm.workspace = true
delegate.workspace = true
minijinja = { workspace = true, features = ["loader"] }
minijinja-embed.workspace = true 
serde.workspace = true

[build-dependencies]
minijinja-embed.workspace = true 

[lints]
workspace = true

