[package]

name = "cpclib-xfer"
version.workspace = true
description = "cpclib libraries related to snapshots"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[package.metadata.workspaces]
independent = true

[dependencies]
cpclib-disc.workspace = true
cpclib-sna.workspace = true
cpclib-common = {workspace = true, features=["network"]}

camino-tempfile.workspace = true
arrayref.workspace = true
cfg-if.workspace = true
custom_error.workspace = true
delegate.workspace = true
either.workspace = true
getset.workspace = true
#memchr.workspace = true
serde.workspace = true

path-absolutize = { workspace = true, optional = false }
curl = { workspace = true, optional = false }


[build-dependencies]
built.workspace = true

