name: Rust

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, i686-pc-windows-gnu]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
            toolchain: nightly
            profile: minimal
            target: ${{matrix.target}}
    - name: Dependencies
      run: sudo apt update && sudo apt install libgtk-3-dev libcogl-pango-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev
    - name: Build
      run: cargo +nightly build --bins --release
    - name: Run tests
      if: ${{ matrix.target }}  == x86_64-unknown-linux-gnu
      run: cargo +nightly test --all-features
    - name: Basm tests
      if: ${{ matrix.target }} == x86_64-unknown-linux-gnu
      run: cd basm/tests/asm && ./launch_tests.sh
    - uses: ncipollo/release-action@v1
      if: ${{ matrix.target }}== x86_64-unknown-linux-gnu 
      with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          allowUpdates: true
          removeArtifacts: false
          prerelease: false
          draft: true
          tag: latest
          name: "Linux Development Build"
          artifacts: |
            target/release/basm,
            target/release/visual-basm,
            target/release/bdasm,
            target/release/catalog,
            target/release/hideur,
            target/release/imgconverter,
            target/release/snapshot,
            target/release/locomotive
    - uses: ncipollo/release-action@v1
      if: ${{ matrix.target }}== i686-pc-windows-gnu 
      with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          allowUpdates: true
          removeArtifacts: false
          prerelease: false
          draft: true
          tag: latest
          name: "Windows Development Build"
          artifacts: |
            target/i686-pc-windows-gnu/release/basm,
            target/i686-pc-windows-gnu/release/visual-basm,
            target/i686-pc-windows-gnu/release/bdasm,
            target/i686-pc-windows-gnu/release/catalog,
            target/i686-pc-windows-gnu/release/hideur,
            target/i686-pc-windows-gnu/release/imgconverter,
            target/i686-pc-windows-gnu/release/snapshot,
            target/i686-pc-windows-gnu/release/locomotive
  
