[package]
name = "cpclib-rasm-basm-tests"
version.workspace = true
edition.workspace = true

[dependencies]
walkdir = { workspace = true }
camino-tempfile = { workspace = true }
cpclib-bndbuild = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
test-generator = "0.3.1"

[build-dependencies]
build-deps = "0.1.4"
